#line 2 "cool-lex.cc"

#line 4 "cool-lex.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

/* %endif */

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[387] =
    {   0,
        0,    0,    0,    0,    0,    0,    2,    2,   67,   65,
       62,   63,   61,   34,   50,   51,   47,   45,   57,   46,
       55,   48,   44,   54,   49,   56,   60,   59,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       52,   61,   53,   58,   64,   43,   36,   35,   66,   66,
        8,    6,    8,    8,    2,    3,   62,    4,    9,   57,
        1,   44,   54,   49,   11,   12,   10,   59,   32,   32,
       32,   32,   32,   32,    0,   32,   32,   32,   32,    0,
       15,   15,   15,   16,   17,   32,   16,   17,   32,   16,

       32,   32,   32,   32,    0,   32,   32,   32,   32,    0,
       26,   26,   26,   32,   32,    0,   32,   32,    0,   32,
       32,    0,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   15,   33,   15,   15,   16,   17,   33,
       16,   17,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   26,   26,   33,   33,   33,   33,   33,   33,    0,
       33,   33,    0,    0,   16,    0,    0,   17,    0,    0,
       15,   58,   43,   42,   40,   41,   38,   39,   42,    5,
        7,    2,   32,   32,    0,   32,   32,    0,    0,   32,
       32,    0,   32,   32,    0,    0,   32,   32,    0,   32,

       32,    0,    0,   19,   19,   19,   32,   32,    0,   19,
       27,   27,   27,   29,   29,   29,   27,   32,   32,    0,
       32,   32,    0,   32,   32,    0,   33,   33,   33,   33,
       33,   33,   33,   33,   33,    0,   33,   33,   33,   33,
       33,   19,   33,   19,   33,   27,   29,   27,   29,   33,
       33,   33,   33,    0,   33,   33,    0,   33,   33,   19,
        0,    0,    0,   29,    0,    0,    0,   19,   19,   37,
       24,   24,   24,   32,   32,    0,   24,   14,   14,   14,
       25,   25,   25,   14,   32,   32,    0,   32,   32,    0,
        0,   20,   20,   20,   21,   21,   21,   22,   22,   22,

       32,   32,    0,   24,   33,   24,   33,   14,   25,   14,
       25,   33,    0,   33,   33,   33,   33,   33,   20,   20,
       21,   21,   22,   30,   30,   22,   30,   22,   33,   33,
       22,   14,   20,   25,   25,   14,   14,   21,   14,   13,
       13,   13,   32,   32,    0,   32,   32,    0,    0,   23,
       23,   23,   13,   13,   31,   31,   31,   33,   33,   33,
       33,   23,   23,   13,   32,   32,    0,   28,   28,   28,
       28,   33,   28,   33,   28,   32,   32,    0,   33,   33,
       18,   18,   18,   18,   18,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    4,    4,    4,    4,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
       18,   19,    4,   20,   21,   22,   23,   24,   25,   26,
       22,   27,   28,   22,   22,   29,   22,   30,   31,   32,
       22,   33,   34,   35,   36,   37,   38,   22,   22,   22,
        4,   39,    4,    4,   40,    4,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   47,   47,   50,   47,   51,
       52,   53,   47,   54,   55,   56,   57,   58,   59,   47,
       47,   47,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3
    } ;

static yyconst flex_int16_t yy_base[393] =
    {   0,
        0,    0,   62,   63,   66,   67,  197,  195,  195, 1153,
      191, 1153, 1153, 1153,  184, 1153,  183, 1153,  179,  177,
     1153, 1153,  170,  163,  160,   60,  134,  111,  114,   55,
       48,   51,   60,   62,  149,   71,   52,   72,  148,  197,
      156,  152,  236,  153,  234,  235,  232,   58,  240,  155,
     1153,  281, 1153,   67, 1153,    0, 1153, 1153,  292, 1153,
     1153, 1153,  117,  117,    0, 1153,  120, 1153, 1153,  108,
     1153,   81,   77,   75, 1153, 1153, 1153,   68,  336,    0,
      228,  263,  237,  278,  354,  280,  279,  289,  284,  355,
        0,    0, 1153,    0,  242,  154,    0,  350,  291,  356,

       73,  230,  344,  285,  347,  359,  345,  364,  351,  384,
        0,    0, 1153,  390,  395,  396,  388,  399,  405,  403,
      404,  406,  427,    0,  453,  468,  456,  471,  460,  472,
      461,  477,  470,    0,  473,    0,  474,    0,  478,  400,
        0,  479,  401,  469,  476,  501,  511,  505,  509,  508,
      512,    0,    0,  519,  522,  516,  518,  531,  524,  553,
      554,  556,  552,  562, 1153,  563,  575,  572,  591,  590,
      632,   22,    0, 1153, 1153, 1153, 1153, 1153,   76, 1153,
     1153,    0,  594,  600,  604,  601,  603,  634,  649,  647,
      651,  653,  656,  659,  662,  684,  661,  676,  686,  672,

      682,  687,  701,    0,    0, 1153,  683,  696,  698,  703,
        0,    0, 1153,    0,    0, 1153, 1153,  711,  713,  721,
      722,  724,  725,  729,  731,  737,  743,  736,  744,  746,
      768,  771,  770,  773,  765,  766,  769,  777,  781,  783,
      787,    0,  793,    0,  803,    0,    0,    0,    0,  790,
      807,  811,  792,  798,  815,  822,  830,  821,  823, 1153,
      848,  824,  857,  858,  869,  870,  871, 1153,  910, 1153,
        0,    0, 1153,  840,  868,  888,  890,    0,    0, 1153,
        0,    0, 1153, 1153,  873,  893,  903,  889,  909,  918,
      940,    0,    0, 1153,    0,    0, 1153,    0,    0, 1153,

      927,  931,  941,    0,  914,    0,  943,    0,    0,    0,
        0,  955,  958,  960,  945,  946,  954,  962,    0,    0,
        0,    0,    0,    0, 1153,    0,    0, 1153,  968,  972,
      985,  957, 1153,  986,  988, 1153,  987,  999, 1017,    0,
        0, 1153, 1003, 1004, 1006,  610, 1012, 1013, 1035,    0,
        0, 1153,    0,    0,    0, 1153,    0, 1026, 1037, 1040,
     1046,    0,    0, 1064,  859, 1041, 1048,    0,    0, 1153,
     1050, 1056,    0, 1058,    0, 1060, 1061, 1065, 1069, 1076,
        0,    0, 1153,    0,    0, 1153, 1137, 1140, 1143,   79,
     1146, 1149

    } ;

static yyconst flex_int16_t yy_def[393] =
    {   0,
      386,    1,  387,  387,  388,  388,  389,  389,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,  386,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
      386,  386,  386,  386,  386,  390,  386,  386,  391,  386,
      386,  386,  386,  386,  392,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,   29,   29,
       29,   29,   79,   79,  386,   29,   29,   79,   79,  386,
       29,   79,  386,   29,   29,   29,   79,   79,   79,  386,

       29,   29,   79,   79,  386,   29,   29,   79,   79,  386,
       29,   79,  386,   29,   79,  386,   29,   79,  386,   29,
       79,  386,   40,   40,  123,  123,   40,   40,  123,  123,
       40,   40,  123,  123,   40,   40,  386,  123,  123,  123,
       40,   40,   40,  123,  123,   40,   40,  123,  123,   40,
       40,  123,   40,  123,   40,  123,  123,   40,   40,  386,
      123,   40,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  390,  386,  386,  386,  386,  386,  386,  386,
      386,  392,   29,   79,  386,   29,   79,  386,  386,   29,
       79,  386,   29,   79,  386,  386,   29,   79,  386,   29,

       79,  386,  386,   29,   79,  386,   29,   79,  386,  386,
       29,   79,  386,   29,   79,  386,  386,   29,   79,  386,
       29,   79,  386,   29,   79,  386,  123,  123,   40,   40,
      123,  123,   40,   40,  123,  386,   40,  123,  123,   40,
       40,  123,  123,   40,   40,  123,  123,   40,   40,  123,
       40,  123,  123,  386,   40,   40,  386,  123,   40,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
       29,   79,  386,   29,   79,  386,  386,   29,   79,  386,
       29,   79,  386,  386,   29,   79,  386,   29,   79,  386,
      386,   29,   79,  386,   29,   79,  386,   29,   79,  386,

       29,   79,  386,  123,  123,   40,   40,  123,  123,   40,
       40,  123,  386,   40,  123,  123,   40,   40,  123,   40,
      123,   40,  123,  123,  386,   40,   40,  386,  123,   40,
      386,  386,  386,  386,  386,  386,  386,  386,  386,   29,
       79,  386,   29,   79,  386,   29,   79,  386,  386,   29,
       79,  386,  123,   40,  123,  386,   40,  123,  123,   40,
       40,  123,   40,  386,   29,   79,  386,   29,   79,  386,
      386,  123,  123,   40,   40,   29,   79,  386,  123,   40,
       29,   79,  386,  123,   40,    0,  386,  386,  386,  386,
      386,  386

    } ;

static yyconst flex_int16_t yy_nxt[1218] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   13,   28,
       29,   29,   30,   29,   31,   32,   29,   33,   34,   35,
       36,   37,   29,   29,   38,   29,   29,   39,   13,   13,
       40,   40,   41,   40,   42,   43,   40,   40,   44,   45,
       46,   47,   48,   40,   40,   49,   40,   40,   50,   51,
       52,   53,   54,   55,   57,   57,   58,   58,   62,   62,
       75,   63,   63,   64,   64,   81,   86,   76,   91,  173,
      270,   87,  114,   82,  172,   94,  101,   78,  154,   95,
       74,   73,  102,   96,   72,   83,  111,   88,  117,   92,

       59,   59,   89,  115,   84,   97,  103,  204,   90,  155,
       98,   93,  116,  104,   99,   85,  112,   70,  116,  118,
      100,   67,  105,  181,  180,   60,   60,   79,  205,  172,
       78,  113,  119,  206,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   77,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,  106,  120,   74,  125,   73,  138,  107,
      129,  161,  139,   72,  126,  130,  140,   71,   70,   69,
      200,   68,   67,  108,  386,  121,  127,   66,  141,   66,

      109,  131,  162,  142,  386,  128,  132,  143,  122,  110,
      123,  201,   90,  100,  202,  122,   85,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  386,  123,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  133,  152,  144,  148,
      207,  183,  386,  134,  145,  149,  156,  386,  197,  386,
      184,  386,  157,  386,  386,  386,  135,  153,  146,  150,
      386,  208,  184,  186,  136,  147,  151,  158,  185,  198,
      209,  184,  113,  159,  105,  110,  137,  185,  187,  193,

      160,  163,  199,  187,  194,  164,  165,  166,   93,  167,
      168,  169,  386,  190,  170,  208,  386,  386,  187,  194,
      386,  163,  191,  188,  194,  164,  165,  201,  166,   93,
      167,  168,  169,  175,  191,  170,  208,  176,  188,  195,
      192,  171,  177,  191,  195,  209,  386,  178,  201,  192,
      386,  202,  386,  386,  386,  179,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,  188,  195,  198,  209,  205,  214,
      386,  206,  199,  386,  386,  215,  386,  185,  192,  386,
      386,  386,  202,  386,  188,  195,  211,  198,  209,  205,

      215,  212,  206,  199,  206,  216,  215,  210,  185,  192,
      199,  216,  221,  202,  189,  196,  203,  212,  216,  213,
      218,  213,  212,  222,  213,  219,  220,  386,  386,  223,
      224,  225,  222,  226,  386,  386,  239,  239,  386,  216,
      386,  219,  213,  222,  217,  386,  219,  220,  223,  223,
      220,  225,  225,  386,  226,  220,  220,  239,  241,  223,
      202,  202,  386,  226,  226,  223,  226,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  227,  386,  228,  227,
      386,  228,  232,  231,  231,  386,  386,  232,  235,  386,

      386,  235,  236,  242,  238,  238,  243,  227,  228,  386,
      229,  230,  232,  185,  231,  233,  185,  234,  386,  235,
      192,  192,  237,  236,  242,  238,  240,  243,  188,  206,
      236,  188,  195,  236,  236,  242,  209,  195,  199,  199,
      252,  243,  246,  247,  386,  246,  247,  386,  386,  250,
      386,  386,  250,  253,  386,  252,  244,  386,  386,  253,
      252,  206,  245,  246,  247,  213,  248,  249,  213,  216,
      250,  209,  216,  251,  253,  255,  223,  223,  254,  220,
      256,  258,  220,  258,  254,  185,  386,  223,  254,  386,
      226,  223,  386,  386,  386,  188,  206,  223,  199,  213,

      386,  386,  258,  386,  259,  386,  185,  223,  192,  254,
      195,  226,  185,  257,  226,  188,  226,  206,  271,  199,
      213,  263,  260,  261,  272,  216,  202,  386,  273,  192,
      195,  386,  199,  368,  274,  262,  275,  386,  272,  386,
      386,  386,  263,  386,  272,  386,  216,  202,  273,  386,
      265,  264,  266,  369,  273,  275,  223,  275,  199,  226,
      273,  276,  263,  276,  273,  267,  268,  276,  202,  213,
      370,  278,  266,  273,  386,  279,  223,  280,  281,  199,
      226,  282,  276,  263,  283,  285,  267,  268,  276,  202,
      213,  279,  269,  273,  276,  279,  386,  280,  282,  386,

      286,  282,  288,  276,  283,  286,  283,  280,  280,  277,
      287,  280,  289,  280,  292,  386,  283,  290,  386,  283,
      286,  287,  283,  289,  386,  287,  283,  293,  280,  294,
      287,  290,  290,  289,  294,  293,  287,  386,  290,  295,
      386,  296,  290,  294,  284,  287,  287,  290,  293,  297,
      294,  298,  290,  299,  300,  294,  294,  301,  294,  302,
      296,  291,  296,  294,  386,  303,  386,  304,  304,  305,
      297,  297,  299,  297,  299,  300,  386,  386,  302,  305,
      302,  297,  300,  386,  300,  300,  303,  304,  306,  303,
      305,  303,  308,  309,  308,  309,  276,  303,  312,  313,

      307,  315,  312,  273,  273,  386,  276,  315,  386,  386,
      386,  316,  308,  309,  310,  311,  324,  316,  321,  312,
      313,  315,  325,  314,  319,  313,  313,  317,  280,  313,
      280,  283,  316,  283,  319,  321,  324,  287,  318,  321,
      323,  290,  325,  287,  323,  319,  324,  290,  280,  329,
      297,  329,  325,  294,  325,  320,  322,  276,  325,  300,
      386,  323,  386,  294,  386,  326,  327,  297,  280,  386,
      329,  300,  330,  340,  325,  300,  303,  300,  276,  386,
      300,  303,  325,  303,  332,  297,  297,  386,  294,  294,
      328,  283,  283,  376,  341,  336,  386,  303,  300,  290,

      342,  341,  386,  276,  386,  343,  297,  297,  331,  294,
      294,  283,  283,  386,  377,  336,  346,  333,  333,  378,
      290,  342,  341,  342,  276,  344,  344,  386,  342,  334,
      335,  336,  283,  345,  337,  345,  347,  347,  338,  300,
      290,  294,  342,  276,  342,  348,  344,  353,  342,  348,
      342,  350,  283,  345,  337,  351,  345,  347,  386,  338,
      300,  290,  294,  345,  276,  352,  348,  348,  353,  348,
      339,  351,  345,  359,  342,  351,  353,  358,  348,  355,
      386,  386,  356,  386,  355,  352,  358,  352,  348,  359,
      342,  352,  362,  345,  359,  386,  362,  354,  358,  355,

      349,  352,  356,  342,  357,  345,  348,  360,  386,  352,
      361,  342,  362,  348,  345,  356,  363,  342,  356,  345,
      356,  342,  348,  352,  386,  386,  386,  386,  352,  352,
      365,  366,  352,  367,  348,  369,  370,  386,  386,  386,
      345,  352,  342,  352,  348,  352,  348,  345,  342,  345,
      342,  366,  366,  372,  367,  369,  370,  386,  370,  352,
      373,  352,  367,  367,  367,  348,  367,  372,  386,  373,
      345,  342,  370,  370,  372,  377,  386,  364,  370,  386,
      373,  386,  378,  367,  378,  386,  367,  370,  374,  375,
      379,  367,  379,  381,  382,  371,  377,  370,  383,  386,

      367,  378,  384,  378,  386,  378,  370,  370,  378,  384,
      378,  379,  367,  380,  382,  382,  378,  386,  378,  383,
      383,  383,  386,  384,  371,  383,  386,  386,  386,  383,
      385,  386,  386,  386,  386,  386,  383,   56,   56,   56,
       61,   61,   61,   65,   65,   65,  174,  174,  174,  182,
      386,  182,    9,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386
    } ;

static yyconst flex_int16_t yy_chk[1218] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    3,    4,    5,    6,
       26,    5,    6,    5,    6,   30,   31,   26,   32,  390,
      179,   31,   37,   30,  172,   33,   34,   78,   48,   33,
       74,   73,   34,   33,   72,   30,   36,   31,   38,   32,

        3,    4,   31,   37,   30,   33,   34,  101,   31,   48,
       33,   32,   37,   34,   33,   30,   36,   70,   48,   38,
       33,   67,   34,   64,   63,    3,    4,   29,  101,   54,
       28,   36,   38,  101,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   27,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   35,   39,   25,   41,   24,   44,   35,
       42,   50,   44,   23,   41,   42,   44,   20,   19,   17,
       96,   15,   11,   35,    9,   39,   41,    8,   44,    7,

       35,   42,   50,   44,    0,   41,   42,   44,   39,   35,
       40,   96,   42,   44,   96,   50,   41,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,    0,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   43,   47,   45,   46,
      102,   81,    0,   43,   45,   46,   49,    0,   95,    0,
       83,    0,   49,    0,    0,    0,   43,   47,   45,   46,
        0,  102,   81,   82,   43,   45,   46,   49,   81,   95,
      102,   83,   47,   49,   45,   46,   43,   83,   84,   87,

       49,   52,   95,   82,   89,   52,   52,   52,   52,   52,
       52,   52,    0,   86,   52,  104,    0,    0,   84,   87,
        0,   52,   88,   82,   89,   52,   52,   99,   52,   52,
       52,   52,   52,   59,   86,   52,  104,   59,   84,   87,
       86,   52,   59,   88,   89,  104,    0,   59,   99,   88,
        0,   99,    0,    0,    0,   59,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   85,   90,   98,  105,  103,  107,
        0,  105,  100,    0,    0,  109,    0,   85,   90,    0,
        0,    0,  100,    0,   85,   90,  106,   98,  105,  103,

      107,  108,  105,  100,  103,  107,  109,  105,   85,   90,
       98,  109,  117,  100,   85,   90,  100,  106,  110,  106,
      114,  110,  108,  118,  108,  115,  116,    0,    0,  119,
      120,  121,  117,  122,    0,    0,  140,  143,    0,  110,
        0,  114,  110,  118,  110,    0,  115,  116,  117,  119,
      114,  120,  121,    0,  122,  115,  116,  140,  143,  118,
      140,  143,    0,  120,  121,  119,  122,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  125,    0,  126,  127,
        0,  128,  130,  129,  131,    0,    0,  132,  133,    0,

        0,  135,  137,  144,  139,  142,  145,  125,  126,    0,
      127,  128,  130,  125,  129,  131,  127,  132,    0,  133,
      129,  131,  135,  137,  144,  139,  142,  145,  126,  144,
      133,  128,  130,  135,  137,  146,  145,  132,  139,  142,
      156,  147,  148,  149,    0,  150,  151,    0,    0,  154,
        0,    0,  155,  157,    0,  158,  146,    0,    0,  159,
      156,  146,  147,  148,  149,  148,  150,  151,  150,  149,
      154,  147,  151,  155,  157,  158,  156,  160,  157,  154,
      159,  161,  155,  162,  159,  163,    0,  166,  160,    0,
      166,  158,    0,    0,    0,  167,  164,  160,  168,  164,

        0,    0,  161,    0,  162,    0,  163,  166,  167,  160,
      170,  166,  163,  160,  161,  167,  162,  164,  183,  168,
      164,  169,  164,  166,  184,  169,  170,    0,  185,  167,
      170,    0,  168,  346,  186,  167,  187,    0,  183,    0,
        0,    0,  169,    0,  184,    0,  169,  170,  185,    0,
      170,  169,  171,  346,  183,  186,  171,  187,  171,  171,
      184,  186,  171,  187,  185,  171,  171,  188,  171,  171,
      346,  190,  171,  189,    0,  191,  171,  192,  193,  171,
      171,  194,  189,  171,  195,  197,  171,  171,  188,  171,
      171,  190,  171,  189,  188,  191,    0,  192,  193,    0,

      198,  194,  200,  189,  195,  197,  196,  190,  196,  189,
      199,  191,  201,  192,  207,    0,  193,  202,    0,  194,
      198,  197,  195,  200,    0,  203,  196,  208,  196,  209,
      199,  203,  200,  201,  210,  207,  198,    0,  202,  218,
        0,  219,  201,  207,  196,  203,  199,  202,  208,  220,
      209,  221,  203,  222,  223,  210,  208,  224,  209,  225,
      218,  203,  219,  210,    0,  226,    0,  227,  229,  228,
      220,  218,  221,  219,  222,  223,    0,    0,  224,  230,
      225,  220,  221,    0,  222,  223,  226,  227,  229,  224,
      228,  225,  231,  232,  233,  234,  228,  226,  235,  236,

      230,  238,  237,  227,  229,    0,  230,  240,    0,    0,
        0,  239,  231,  232,  233,  234,  253,  241,  250,  235,
      236,  238,  254,  237,  243,  235,  236,  240,  231,  237,
      233,  232,  239,  234,  245,  251,  253,  238,  241,  250,
      252,  239,  254,  240,  255,  243,  256,  241,  262,  258,
      250,  259,  253,  243,  257,  245,  251,  262,  254,  257,
        0,  252,    0,  245,    0,  255,  256,  251,  262,    0,
      258,  252,  259,  274,  257,  255,  261,  261,  262,    0,
      257,  258,  256,  259,  262,  263,  264,    0,  263,  264,
      257,  265,  266,  365,  274,  267,    0,  261,  261,  265,

      274,  275,    0,  266,    0,  285,  263,  264,  261,  263,
      264,  265,  266,    0,  365,  267,  288,  263,  264,  365,
      265,  276,  275,  277,  266,  286,  285,    0,  275,  265,
      266,  267,  269,  285,  269,  287,  289,  288,  269,  269,
      269,  269,  276,  269,  277,  290,  286,  305,  276,  288,
      277,  301,  269,  286,  269,  302,  287,  289,    0,  269,
      269,  269,  269,  287,  269,  303,  290,  291,  305,  289,
      269,  301,  291,  316,  305,  302,  307,  315,  290,  312,
        0,    0,  313,    0,  314,  303,  317,  301,  291,  318,
      332,  302,  329,  291,  316,    0,  330,  307,  315,  312,

      291,  303,  313,  307,  314,  315,  316,  317,    0,  331,
      318,  332,  329,  334,  317,  312,  330,  332,  313,  337,
      314,  335,  318,  338,    0,    0,    0,    0,  329,  331,
      343,  344,  330,  345,  334,  347,  348,    0,    0,    0,
      337,  339,  335,  338,  339,  331,  334,  337,  335,  339,
      339,  343,  344,  358,  345,  347,  348,    0,  349,  338,
      359,  339,  349,  343,  344,  339,  345,  360,    0,  361,
      339,  339,  347,  348,  358,  366,    0,  339,  349,    0,
      359,    0,  367,  349,  371,    0,  358,  364,  360,  361,
      372,  364,  374,  376,  377,  349,  366,  359,  378,    0,

      360,  366,  379,  367,    0,  371,  361,  364,  367,  380,
      371,  372,  364,  374,  376,  377,  372,    0,  374,  378,
      376,  377,    0,  379,  364,  378,    0,    0,    0,  379,
      380,    0,    0,    0,    0,    0,  380,  387,  387,  387,
      388,  388,  388,  389,  389,  389,  391,  391,  391,  392,
        0,  392,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[66] =
    {   0,
      139,  140,  141,  147,  148,  149,  154,  161,  162,  171,
      172,  173,  178,  179,  180,  181,  182,  183,  184,  185,
      186,  187,  188,  189,  190,  191,  192,  193,  194,  195,
      198,  208,  212,  216,  220,  236,  248,  255,  256,  257,
      258,  260,  268,  279,  283,  284,  285,  286,  289,  290,
      291,  292,  293,  294,  295,  296,  297,  298,  299,  300,
      303,  309,  311,  313,  317
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cool.flex"
/*
%%
 *  The scanner definition for COOL.
 */
/*
 *  Stuff enclosed in %{ %} in the first section is copied verbatim to the
 *  output, so headers and global definitions are placed here to be visible
 * to the code in the file.  Don't remove anything that was here initially
 */
#line 12 "cool.flex"
#include <cool-parse.h>
#include <stringtab.h>
#include <utilities.h>
#include <math.h>
/* The compiler assumes these identifiers. */
#define yylval cool_yylval
#define yylex  cool_yylex

/* Max size of string constants */
#define MAX_STR_CONST 1025
#define YY_NO_UNPUT   /* keep g++ happy */

extern FILE *fin; /* we read from this file */

/* define YY_INPUT so we read from the FILE fin:
 * This change makes it possible to use this scanner in
 * the Cool compiler.
 */
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = fread( (char*)buf, sizeof(char), max_size, fin)) < 0) \
		YY_FATAL_ERROR( "read() in flex scanner failed");

char string_buf[MAX_STR_CONST]; /* to assemble string constants */
char *string_buf_ptr;

int nested_level = 0;

extern int curr_lineno;
extern int verbose_flag;

extern YYSTYPE cool_yylval;

/*
 *  Add Your own definitions here
 */

int curr_str_size = 0;




/*
 * Define names for regular expressions here.
 */
#line 1006 "cool-lex.cc"

#define INITIAL 0
#define str 1
#define comment 2
#define line_comment 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

/* %not-for-header */

    static void yyunput (int c,char *buf_ptr  );
    
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 134 "cool.flex"

 /*
  *  Nested comments
  */

#line 1262 "cool-lex.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 387 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1153 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 66 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 66 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 67 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 139 "cool.flex"
BEGIN(line_comment);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 140 "cool.flex"
/* eat up anything thats not a newline */
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 141 "cool.flex"
{ curr_lineno++;
                          BEGIN(INITIAL);
                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 147 "cool.flex"
{ BEGIN(comment);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 148 "cool.flex"
{ nested_level++; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 149 "cool.flex"
curr_lineno++;
	YY_BREAK
case YY_STATE_EOF(comment):
#line 150 "cool.flex"
{ cool_yylval.error_msg = "EOF in comment";
                          BEGIN(INITIAL);
                          return(ERROR);
                        }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 154 "cool.flex"
{ if (nested_level > 0) {
                            nested_level--; 
                          } else {
                            BEGIN(INITIAL);
                          }
                        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 161 "cool.flex"
{}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 162 "cool.flex"
{ cool_yylval.error_msg = "Unmatched *)";
                          return (ERROR);
                        }
	YY_BREAK
/*
  *  The multiple-character operators.
  */
case 10:
YY_RULE_SETUP
#line 171 "cool.flex"
{ return (DARROW); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 172 "cool.flex"
{ return (ASSIGN); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 173 "cool.flex"
{ return (LE); }
	YY_BREAK
/*
  * Keywords are case-insensitive except for the values true and false,
  * which must begin with a lower-case letter.
  */
case 13:
YY_RULE_SETUP
#line 178 "cool.flex"
{ return (CLASS); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 179 "cool.flex"
{ return (ELSE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 180 "cool.flex"
{ return (FI); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 181 "cool.flex"
{ return (IF); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 182 "cool.flex"
{ return (IN); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 183 "cool.flex"
{ return (INHERITS); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 184 "cool.flex"
{ return (LET); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 185 "cool.flex"
{ return (LOOP); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 186 "cool.flex"
{ return (POOL); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 187 "cool.flex"
{ return (THEN); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 188 "cool.flex"
{ return (WHILE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 189 "cool.flex"
{ return (CASE); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 190 "cool.flex"
{ return (ESAC); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 191 "cool.flex"
{ return (OF); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 192 "cool.flex"
{ return (NEW); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 193 "cool.flex"
{ return (ISVOID); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 194 "cool.flex"
{ return (NOT); } 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 195 "cool.flex"
{ cool_yylval.boolean = true;
                  return (BOOL_CONST);
                }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 198 "cool.flex"
{ cool_yylval.boolean = false;
                  return (BOOL_CONST);
                }
	YY_BREAK
/*
  *  String constants (C syntax)
  *  Escape sequence \c is accepted for all characters c. Except for 
  *  \n \t \b \f, the result is c.
  *
  */
case 32:
YY_RULE_SETUP
#line 208 "cool.flex"
{ cool_yylval.symbol = inttable.add_string(yytext);
                  return (TYPEID);
                }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 212 "cool.flex"
{ cool_yylval.symbol = inttable.add_string(yytext);
                  return (OBJECTID);
                }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 216 "cool.flex"
{ string_buf_ptr = string_buf;
                  BEGIN(str);
                }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 220 "cool.flex"
{ 
                 if (curr_str_size > 1024) {
                    cool_yylval.error_msg = "String constant too long";
                    BEGIN(INITIAL);
                    *string_buf_ptr = '\0';
                    curr_str_size = 0;
                    return(ERROR);
                 } else { 
                  curr_str_size = 0;
                  BEGIN(INITIAL);
                  *string_buf_ptr = '\0';
                  cool_yylval.symbol = inttable.add_string(string_buf);
                  return(STR_CONST);
                 }
                }
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 236 "cool.flex"
{ cool_yylval.error_msg = "Unterminated string constant";
                  BEGIN(INITIAL);
                  *string_buf_ptr = '\0';
                  return (ERROR); 
                }
	YY_BREAK
case YY_STATE_EOF(str):
#line 242 "cool.flex"
{ cool_yylval.error_msg = "EOF in string constant";
                  BEGIN(INITIAL);
                  *string_buf_ptr = '\0';
                  return(ERROR);
                }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 248 "cool.flex"
{ 
                  cool_yylval.error_msg = "String contains null character.";
                  BEGIN(INITIAL);
                  *string_buf_ptr = '\0';
                  return(ERROR);
                 }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 255 "cool.flex"
{curr_str_size++; *string_buf_ptr++ = '\n';}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 256 "cool.flex"
*string_buf_ptr++ = '\t';
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 257 "cool.flex"
*string_buf_ptr++ = '\b';
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 258 "cool.flex"
*string_buf_ptr++ = '\f';
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 260 "cool.flex"
{   if (yytext[1] == '\n') {
                        curr_lineno++;
                    }
                    curr_str_size++;
                    *string_buf_ptr++ = yytext[1];
                }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 268 "cool.flex"
{   
                   char *yptr = yytext;
                   
                   while ( *yptr ) {
                       curr_str_size++;
                       *string_buf_ptr++ = *yptr++;
                   }
                }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(line_comment):
#line 277 "cool.flex"
{ yyterminate(); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 279 "cool.flex"
{ cool_yylval.symbol = inttable.add_string(yytext); 
                  return (INT_CONST); 
                }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 283 "cool.flex"
{ return(43); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 284 "cool.flex"
{ return(45); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 285 "cool.flex"
{ return(42); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 286 "cool.flex"
{ return(47); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 289 "cool.flex"
{ return(59); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 290 "cool.flex"
{ return(40); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 291 "cool.flex"
{ return(41); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 292 "cool.flex"
{ return(123);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 293 "cool.flex"
{ return(125);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 294 "cool.flex"
{ return(58); }         
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 295 "cool.flex"
{ return(46); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 296 "cool.flex"
{ return(60); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 297 "cool.flex"
{ return(44); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 298 "cool.flex"
{ return(126);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 299 "cool.flex"
{ return(64); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 300 "cool.flex"
{ return(61); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 303 "cool.flex"
{ cool_yylval.error_msg = yytext;
                  return(ERROR);
                }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 309 "cool.flex"

	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 311 "cool.flex"
{ curr_lineno++; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 313 "cool.flex"
{ cool_yylval.error_msg = "Null char present.";
                  return(ERROR);
                }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 317 "cool.flex"
{ cool_yylval.error_msg = yytext;
                  return(ERROR);
                }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 320 "cool.flex"
ECHO;
	YY_BREAK
#line 1806 "cool-lex.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 64);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 387 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 64;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 387 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 386);

	return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

    static void yyunput (int c, register char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* %if-c-only */

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* %endif */

/* %if-c++-only */
/* %endif */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 320 "cool.flex"
